// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate/generate/db push) uses the DIRECT Neon endpoint —
    // the -pooler endpoint runs PgBouncer in transaction mode and can't
    // execute schema-migration operations. Runtime Next.js still reads
    // DATABASE_URL (pooler) directly in lib/prisma.ts — no runtime change.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
